# NUMPY
- Numpy is a general purpose array-processing package. It provies a high-performance multidimentional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python

# What is an array
- An array is a data structure that stires value of same data type. In python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [2]:
#Initially import numpy
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
my_lst = [1, 2, 3, 4, 5]
arr = np.array(my_lst)

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
# Multinested array from lists
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [2, 4, 6, 8, 10]
my_lst3 = [3, 6, 9, 12, 15]

arr = np.array([my_lst1, my_lst2, my_lst3])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  3,  6],
       [ 9, 12, 15]])

In [13]:
# Check the shape of array
arr.shape

(3, 5)

In [15]:
print(arr.shape)

(3, 5)


In [16]:
arr.reshape(5, 4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [17]:
arr.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  3,  6,  9, 12, 15]])

In [18]:
arr.shape

(3, 5)

## Indexing in Arrays

In [19]:
# Accessing the array elements
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [25]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
arr1[0]

np.int64(1)

In [28]:
print(arr1[0])

1


In [24]:
# Indexing for multidimention
# arr[:,:] It give all rows and cols
# arr[0:2,0:2 It give two rows and two cols from the multidimentional array

In [29]:
arr

array([1, 2, 3, 4, 5])

In [30]:
# multidimentional array
my_lst4 = [1, 3, 5, 7, 9]
my_lst5 = [2, 4, 6, 8, 10]
my_lst6 = [1, 4, 7, 10, 13]

my_arr = np.array([my_lst4, my_lst5, my_lst6])
my_arr

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 1,  4,  7, 10, 13]])

In [31]:
type(my_arr)

numpy.ndarray

In [32]:
my_arr[:,:]

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 1,  4,  7, 10, 13]])

In [1]:
my_arr[0:2,0:2]

NameError: name 'my_arr' is not defined

In [34]:
my_arr[1:3,3:5]

array([[ 8, 10],
       [10, 13]])